# Generated by Django 4.0.5 on 2022-06-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('url', models.CharField(default='', max_length=600)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='api.project')),
            ],
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
